CC=gcc
CFLAGS=-I.

all : mutex fact deadlock

mutex :  
	$(CC) -o mutex mutex.c $(CFLAGS) -lpthread

fact :  
	$(CC) -o fact fact.c $(CFLAGS) -lpthread

deadlock :  
	$(CC) -o deadlock deadlock.c $(CFLAGS) -lpthread